import style from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";

import Banner from "@/Componentes/Banner";
import Cardapio from "@/Componentes/Cardapio";

import { useState } from 'react';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const lightMode = 'light';
  const darkMode = 'dark'

  const [estilo, setEstilo] = useState(false);

  function handleMudarEstilo() {
    setEstilo(!estilo)
  }

  return (
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${style.main} ${inter.className} ${style[estilo ? darkMode : lightMode]}`}>

        <Banner
          funcao={handleMudarEstilo}
        />

        <Cardapio />

      </main>

    </>
  );
}
