
// Importação de componentes e Mecanismos de estilização
import Cardapio from "@/Componentes/Cardapio";

// Importação de bibliotecas e / ou métodos
import Head from "next/head";

export default function Home() {

  return (
    <>
      <Head>
        <title>Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet" />
        <link rel="icon" href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV1aa4MXV0Co6Zvwn7vKQDgAFcsEERbT2WaQwvpdf5Gg&s" />
      </Head>



      <body>

        <Cardapio />

      </body>



    </>
  );
}
